#!/usr/bin/env python3
"""Extract object crops and object-local matrices from stored debug artifacts.

The command is artifact-only. It consumes ``01-geometry`` outputs plus the
canonical topology generated by ``annotate_pixel_partition_topology.py`` and
publishes one directory per recursively isolated object. It never reruns
geometry, OCR, block planning, or document assembly.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
import tempfile
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPOSITORY_ROOT / "ocr"))

from app.sparse_pipeline.recursive_object_partition import (  # noqa: E402
    NumericCell,
    NumericRow,
    PartitionMatrixBasis,
    PartitionNode,
    PartitionSegment,
    PartitionedObject,
    RuledNetwork,
    has_two_dimensional_object_extent,
    partition_recursive_objects,
    table_upper_left_boundary,
)
from app.sparse_pipeline.sparse_topology import (  # noqa: E402
    EMPTY,
    SpatialSlot,
    encode_spatial_topology,
    sparse_code_components,
)

BoxTuple = tuple[int, int, int, int]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Extract recursively isolated objects from stored topology"
    )
    parser.add_argument("stage_dir", type=Path)
    parser.add_argument(
        "--topology-dir",
        type=Path,
        help="directory containing topology artifacts when stages are separated",
    )
    parser.add_argument("--topology", default="sparse-topology-canonical.json")
    parser.add_argument("--segments", default="segments.jsonl")
    parser.add_argument("--nodes", default="nodes.jsonl")
    parser.add_argument("--image", default="aligned.png")
    parser.add_argument("--ownership", default="ownership-plain.png")
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--replace", action="store_true")
    return parser.parse_args()


def _read_json(path: Path) -> object:
    return json.loads(path.read_text(encoding="utf-8"))


def _read_jsonl(path: Path) -> tuple[dict[str, object], ...]:
    return tuple(
        json.loads(line)
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    )


def _write_json(path: Path, value: object) -> None:
    path.write_text(
        json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def _bbox(value: object, *, name: str) -> BoxTuple:
    if not isinstance(value, dict):
        raise ValueError(f"{name} must be an object")
    box = tuple(value.get(key) for key in ("left", "top", "right", "bottom"))
    if (
        len(box) != 4
        or any(type(item) is not int for item in box)
        or box[0] >= box[2]
        or box[1] >= box[3]
    ):
        raise ValueError(f"{name} must be a positive integer bbox")
    return box  # type: ignore[return-value]


def _list_box(value: object, *, name: str) -> BoxTuple:
    if (
        not isinstance(value, list)
        or len(value) != 4
        or any(type(item) is not int for item in value)
        or value[0] >= value[2]
        or value[1] >= value[3]
    ):
        raise ValueError(f"{name} must be a positive four-item box")
    return tuple(value)  # type: ignore[return-value]


def _interval(value: object, *, name: str) -> tuple[int, int]:
    if (
        not isinstance(value, list)
        or len(value) != 2
        or any(type(item) is not int for item in value)
        or value[0] >= value[1]
    ):
        raise ValueError(f"{name} must be a positive interval")
    return value[0], value[1]


def _parse_topology(value: object) -> tuple[
    tuple[NumericRow, ...],
    tuple[RuledNetwork, ...],
]:
    if not isinstance(value, dict) or not isinstance(value.get("rows"), list):
        raise ValueError("canonical topology is invalid")
    rows: list[NumericRow] = []
    previous_bottom: int | None = None
    for expected, raw_row in enumerate(value["rows"]):
        if not isinstance(raw_row, dict) or raw_row.get("row") != expected:
            raise ValueError("topology rows must be canonical")
        top, bottom = _interval(raw_row.get("y"), name="topology y")
        if previous_bottom is not None and top < previous_bottom:
            raise ValueError("topology rows must be monotone and non-overlapping")
        previous_bottom = bottom
        raw_segments = raw_row.get("segments")
        if not isinstance(raw_segments, list):
            raise ValueError("topology row segments must be a list")
        cells: list[NumericCell] = []
        previous_right: int | None = None
        for raw_cell in raw_segments:
            if not isinstance(raw_cell, dict):
                raise ValueError("topology cell must be an object")
            left, right = _interval(raw_cell.get("x"), name="topology x")
            code = raw_cell.get("code")
            state = raw_cell.get("state")
            if type(code) is not int or state not in ("payload", "empty"):
                raise ValueError("topology code or state is invalid")
            components = sparse_code_components(code)
            if code != 0 and not components:
                raise ValueError("topology code is outside the additive alphabet")
            is_empty = state == "empty"
            if is_empty != (7 in components) or (is_empty and 5 in components):
                raise ValueError("topology empty state disagrees with its code")
            if previous_right is not None and left < previous_right:
                raise ValueError("topology cells must be ordered and non-overlapping")
            if 5 in components and (
                not cells or cells[-1].empty or cells[-1].bbox[2] != left
            ):
                raise ValueError("merge-left must resolve to a finite payload cell")
            previous_right = right
            cells.append(
                NumericCell(
                    bbox=(left, top, right, bottom),
                    code=code,
                    empty=state == "empty",
                )
            )
        if rows:
            upper = rows[-1]
            for cell in cells:
                if 3 not in sparse_code_components(cell.code):
                    continue
                if upper.bottom != top or not any(
                    upper_cell.empty == cell.empty
                    and max(upper_cell.bbox[0], cell.bbox[0])
                    < min(upper_cell.bbox[2], cell.bbox[2])
                    for upper_cell in upper.cells
                ):
                    raise ValueError(
                        "merge-up must resolve to a finite cell in the previous row"
                    )
        compressed_codes = raw_row.get("compressed_codes")
        expected_codes = [*(cell.code for cell in cells), None]
        if compressed_codes != expected_codes:
            raise ValueError("compressed topology codes disagree with finite cells")
        null_tail = raw_row.get("null_tail")
        if (
            not isinstance(null_tail, dict)
            or null_tail.get("from_column") != len(cells)
            or type(null_tail.get("through_column_exclusive")) is not int
            or null_tail["through_column_exclusive"] < len(cells)
            or null_tail.get("repeat_last_code")
            != (cells[-1].code if cells else None)
        ):
            raise ValueError("topology null tail is invalid")
        rows.append(NumericRow(expected, top, bottom, tuple(cells)))
    raw_ruled_networks = value.get("ruled_networks", [])
    raw_table_regions = value.get("table_regions", [])
    if not isinstance(raw_ruled_networks, list) or not isinstance(
        raw_table_regions, list
    ):
        raise ValueError("topology regions must be lists")
    raw_networks = [
        *((raw, "connected-ruled-network") for raw in raw_ruled_networks),
        *((raw, "v16-recursive-row-and-x-track-lattice") for raw in raw_table_regions),
    ]
    networks: list[RuledNetwork] = []
    for raw, default_evidence in raw_networks:
        if not isinstance(raw, dict):
            raise ValueError("ruled network must be an object")
        x_lines = raw.get("x_lines")
        y_lines = raw.get("y_lines")
        if (
            not isinstance(x_lines, list)
            or not isinstance(y_lines, list)
            or len(x_lines) < 2
            or len(y_lines) < 2
            or any(type(item) is not int for item in (*x_lines, *y_lines))
        ):
            raise ValueError("ruled network lines are invalid")
        networks.append(
            RuledNetwork(
                bbox=_list_box(raw.get("bbox"), name="network bbox"),
                x_lines=tuple(x_lines),
                y_lines=tuple(y_lines),
                evidence=str(raw.get("evidence", default_evidence)),
            )
        )
    return tuple(rows), tuple(networks)


def _parse_segments(
    values: tuple[dict[str, object], ...],
    *,
    bbox_overrides: dict[str, BoxTuple] | None = None,
) -> tuple[PartitionSegment, ...]:
    result: list[PartitionSegment] = []
    for value in values:
        segment_id = value.get("segment_id")
        parent_path = value.get("parent_path")
        if (
            type(segment_id) is not str
            or not isinstance(parent_path, list)
            or any(type(item) is not str for item in parent_path)
        ):
            raise ValueError("segment identity or parent path is invalid")
        result.append(
            PartitionSegment(
                segment_id=segment_id,
                bbox=(
                    bbox_overrides[segment_id]
                    if bbox_overrides is not None
                    and segment_id in bbox_overrides
                    else _bbox(value.get("bbox"), name="segment bbox")
                ),
                parent_path=tuple(parent_path),
            )
        )
    return tuple(result)


def _parse_nodes(
    values: tuple[dict[str, object], ...],
) -> tuple[PartitionNode, ...]:
    result: list[PartitionNode] = []
    for value in values:
        node_id = value.get("node_id")
        axis = value.get("axis")
        child_ids = value.get("child_ids")
        segment_ids = value.get("segment_ids")
        separator_boxes = value.get("separator_boxes")
        if (
            type(node_id) is not str
            or axis not in (None, "rows", "columns")
            or not isinstance(child_ids, list)
            or not isinstance(segment_ids, list)
            or not isinstance(separator_boxes, list)
            or any(type(item) is not str for item in (*child_ids, *segment_ids))
        ):
            raise ValueError("recursive node is invalid")
        result.append(
            PartitionNode(
                node_id=node_id,
                bbox=_bbox(value.get("bbox"), name="node bbox"),
                axis=axis,
                child_ids=tuple(child_ids),
                segment_ids=tuple(segment_ids),
                separator_boxes=tuple(
                    _bbox(box, name="separator bbox") for box in separator_boxes
                ),
            )
        )
    return tuple(result)


def _intersects(first: BoxTuple, second: BoxTuple) -> bool:
    return (
        max(first[0], second[0]) < min(first[2], second[2])
        and max(first[1], second[1]) < min(first[3], second[3])
    )


def _source_payload_components(
    rows: tuple[NumericRow, ...],
) -> dict[tuple[int, int], int]:
    """Recover conservative physical payload identities from stored edges."""

    positions = {
        (row_index, cell_index): index
        for index, (row_index, cell_index) in enumerate(
            (row_index, cell_index)
            for row_index, row in enumerate(rows)
            for cell_index, cell in enumerate(row.cells)
            if not cell.empty
        )
    }
    parents = list(range(len(positions)))

    def find(value: int) -> int:
        while parents[value] != value:
            parents[value] = parents[parents[value]]
            value = parents[value]
        return value

    def union(first: int, second: int) -> None:
        first_root = find(first)
        second_root = find(second)
        if first_root != second_root:
            parents[second_root] = first_root

    for row_index, row in enumerate(rows):
        for cell_index, cell in enumerate(row.cells):
            current = positions.get((row_index, cell_index))
            if current is None or 5 not in sparse_code_components(cell.code):
                continue
            previous = positions.get((row_index, cell_index - 1))
            if (
                previous is not None
                and cell_index > 0
                and row.cells[cell_index - 1].bbox[2] == cell.bbox[0]
            ):
                union(previous, current)

    for row_index, row in enumerate(rows):
        for cell_index, cell in enumerate(row.cells):
            current = positions.get((row_index, cell_index))
            if current is None or 3 not in sparse_code_components(cell.code):
                continue
            if row_index == 0 or rows[row_index - 1].bottom != row.top:
                continue
            upper = tuple(
                positions[(row_index - 1, upper_index)]
                for upper_index, upper_cell in enumerate(rows[row_index - 1].cells)
                if (row_index - 1, upper_index) in positions
                and max(upper_cell.bbox[0], cell.bbox[0])
                < min(upper_cell.bbox[2], cell.bbox[2])
            )
            if upper and len({find(value) for value in upper}) == 1:
                for value in upper:
                    union(value, current)
    roots = {value: find(index) for value, index in positions.items()}
    canonical = {
        root: canonical_index
        for canonical_index, root in enumerate(sorted(set(roots.values())))
    }
    return {position: canonical[root] for position, root in roots.items()}


def _local_matrix(
    *,
    document_object: PartitionedObject,
    rows: tuple[NumericRow, ...],
    segment_by_id: dict[str, PartitionSegment],
    networks: tuple[RuledNetwork, ...],
) -> dict[str, object]:
    crop_left, crop_top, _, _ = document_object.bbox
    matrix_left, matrix_top, matrix_right, matrix_bottom = document_object.matrix_bbox
    table_network = None
    if document_object.matrix_basis is PartitionMatrixBasis.RULE_LATTICE:
        matching_networks = tuple(
            network
            for network in networks
            if (
                network.x_lines[0] == matrix_left
                and network.x_lines[-1] == matrix_right
                and network.y_lines[0] <= matrix_top < matrix_bottom
                and matrix_bottom <= network.y_lines[-1]
                and matrix_top in network.y_lines
                and matrix_bottom in network.y_lines
            )
        )
        if len(matching_networks) != 1:
            raise ValueError("table object must identify one local matrix lattice")
        table_network = matching_networks[0]
    source_components = _source_payload_components(rows)
    embedded_payload_ids = {
        segment_id
        for segment_id in document_object.segment_ids
        for row in rows
        for cell in row.cells
        if cell.empty
        and cell.bbox[0] <= segment_by_id[segment_id].bbox[0]
        and segment_by_id[segment_id].bbox[2] <= cell.bbox[2]
        and cell.bbox[1] <= segment_by_id[segment_id].bbox[1]
        and segment_by_id[segment_id].bbox[3] <= cell.bbox[3]
    }
    materialized: list[tuple[int, int, tuple[SpatialSlot, ...], list[list[str]]]] = []
    if table_network is not None:
        # Concurrent flow outside a finite table may subdivide page topology
        # rows at its own baselines.  Those subdivisions correctly carry 3/8
        # in the page matrix, but they are not rows of the cropped table.
        # Rebuild the object from its own horizontal rule lattice.  A sparse
        # card grid can have only one physical interval below the detected
        # 0/5 -> 3/8 anchor.  In that one case retain the anchor pair's local
        # canonical boundary as well: otherwise serialization collapses the
        # proven two-row table back to a single unusable 0/5 row.
        boundaries = {
            value
            for value in table_network.y_lines
            if matrix_top <= value <= matrix_bottom
        }
        if len(boundaries) == 2:
            column_intervals = tuple(
                zip(
                    table_network.x_lines,
                    table_network.x_lines[1:],
                )
            )
            candidates = sorted(
                {
                    value
                    for row in rows
                    for value in (row.top, row.bottom)
                    if matrix_top < value < matrix_bottom
                }
                | {
                    value
                    for segment_id in document_object.segment_ids
                    for value in (
                        segment_by_id[segment_id].bbox[1],
                        segment_by_id[segment_id].bbox[3],
                    )
                    if matrix_top < value < matrix_bottom
                }
            )
            minimum_supported_columns = min(
                len(column_intervals),
                max(2, (3 * len(column_intervals) + 4) // 5),
            )
            split_candidates: list[tuple[int, float, int]] = []
            for candidate in candidates:
                above = 0
                below = 0
                for left, right in column_intervals:
                    column_segments = tuple(
                        segment_by_id[segment_id]
                        for segment_id in document_object.segment_ids
                        if _intersects(
                            segment_by_id[segment_id].bbox,
                            (left, matrix_top, right, matrix_bottom),
                        )
                    )
                    above += any(
                        _intersects(
                            segment.bbox,
                            (left, matrix_top, right, candidate),
                        )
                        for segment in column_segments
                    )
                    below += any(
                        _intersects(
                            segment.bbox,
                            (left, candidate, right, matrix_bottom),
                        )
                        for segment in column_segments
                    )
                support = min(above, below)
                if support < minimum_supported_columns:
                    continue
                center_distance = abs(
                    candidate - (matrix_top + matrix_bottom) / 2.0
                )
                split_candidates.append(
                    (support, -center_distance, candidate)
                )
            if split_candidates:
                boundaries.add(max(split_candidates)[2])
            else:
                # If sparse payload occupies too few columns to establish a
                # majority-supported visual boundary, preserve the concrete
                # canonical pair which Stage 6 used to accept the table.
                anchor_boundary = table_upper_left_boundary(
                    rows,
                    table_network,
                )
                if (
                    anchor_boundary is not None
                    and matrix_top < anchor_boundary < matrix_bottom
                ):
                    boundaries.add(anchor_boundary)
        ordered_boundaries = tuple(sorted(boundaries))
        row_intervals = tuple(
            (top, bottom)
            for top, bottom in zip(
                ordered_boundaries,
                ordered_boundaries[1:],
            )
            if top < bottom
        )
    else:
        base_topology_intervals = tuple(
            (max(row.top, matrix_top), min(row.bottom, matrix_bottom))
            for row in rows
            if max(row.top, matrix_top) < min(row.bottom, matrix_bottom)
        )
        topology_boundaries = {
            value for interval in base_topology_intervals for value in interval
        }
        topology_boundaries.update(
            value
            for segment_id in embedded_payload_ids
            for value in (
                segment_by_id[segment_id].bbox[1],
                segment_by_id[segment_id].bbox[3],
            )
            if matrix_top < value < matrix_bottom
        )
        ordered_topology_boundaries = tuple(sorted(topology_boundaries))
        topology_intervals = tuple(
            (top, bottom)
            for top, bottom in zip(
                ordered_topology_boundaries,
                ordered_topology_boundaries[1:],
            )
            if top < bottom
            and any(
                first <= top and bottom <= second
                for first, second in base_topology_intervals
            )
        )
        missing_intervals = tuple(
            (
                max(matrix_top, segment_by_id[segment_id].bbox[1]),
                min(matrix_bottom, segment_by_id[segment_id].bbox[3]),
            )
            for segment_id in document_object.segment_ids
            if not any(
                max(interval[0], segment_by_id[segment_id].bbox[1])
                < min(interval[1], segment_by_id[segment_id].bbox[3])
                for interval in topology_intervals
            )
        )
        extra_boundaries = tuple(sorted({value for pair in missing_intervals for value in pair}))
        extra_intervals = tuple(
            (top, bottom)
            for top, bottom in zip(extra_boundaries, extra_boundaries[1:])
            if top < bottom
            and any(
                max(top, first) < min(bottom, second)
                for first, second in missing_intervals
            )
            and not any(
                max(top, first) < min(bottom, second)
                for first, second in topology_intervals
            )
        )
        row_intervals = tuple(sorted((*topology_intervals, *extra_intervals)))
    for top, bottom in row_intervals:
        if table_network is not None:
            ordered = table_network.x_lines
        else:
            boundaries = {matrix_left, matrix_right}
            matching_rows = tuple(
                row
                for row in rows
                if row.top <= top and bottom <= row.bottom
            )
            for row in matching_rows:
                for cell in row.cells:
                    if cell.bbox[2] <= matrix_left or cell.bbox[0] >= matrix_right:
                        continue
                    boundaries.add(max(matrix_left, cell.bbox[0]))
                    boundaries.add(min(matrix_right, cell.bbox[2]))
            if not matching_rows:
                for segment_id in document_object.segment_ids:
                    segment = segment_by_id[segment_id]
                    if not _intersects(
                        segment.bbox,
                        (matrix_left, top, matrix_right, bottom),
                    ):
                        continue
                    boundaries.add(max(matrix_left, segment.bbox[0]))
                    boundaries.add(min(matrix_right, segment.bbox[2]))
            for segment_id in embedded_payload_ids:
                segment = segment_by_id[segment_id]
                if not _intersects(
                    segment.bbox,
                    (matrix_left, top, matrix_right, bottom),
                ):
                    continue
                boundaries.add(max(matrix_left, segment.bbox[0]))
                boundaries.add(min(matrix_right, segment.bbox[2]))
            ordered = tuple(sorted(boundaries))
        slots: list[SpatialSlot] = []
        owners_by_slot: list[list[str]] = []
        for left, right in zip(ordered, ordered[1:]):
            cell_box = (left, top, right, bottom)
            owners = [
                segment_id
                for segment_id in document_object.segment_ids
                if _intersects(segment_by_id[segment_id].bbox, cell_box)
            ]
            source_cells = tuple(
                (row_index, cell_index, cell)
                for row_index, row in enumerate(rows)
                if row.top <= top and bottom <= row.bottom
                for cell_index, cell in enumerate(row.cells)
                if _intersects(cell.bbox, cell_box)
            )
            embedded_owners = set(owners) & embedded_payload_ids
            centered_owners = {
                segment_id
                for segment_id in owners
                if left
                <= (
                    segment_by_id[segment_id].bbox[0]
                    + segment_by_id[segment_id].bbox[2]
                )
                / 2.0
                < right
                and top
                <= (
                    segment_by_id[segment_id].bbox[1]
                    + segment_by_id[segment_id].bbox[3]
                )
                / 2.0
                < bottom
            }
            explicitly_empty = table_network is None and bool(source_cells) and all(
                cell.empty for _, _, cell in source_cells
            ) and not embedded_owners and not centered_owners
            component_ids = tuple(
                sorted(
                    {
                        source_components[(row_index, cell_index)]
                        for row_index, cell_index, cell in source_cells
                        if not cell.empty
                        and (row_index, cell_index) in source_components
                    }
                )
            )
            if table_network is not None:
                payload_value: object = document_object.object_id
            elif component_ids:
                payload_value = ("source-components", *component_ids)
            else:
                payload_value = ("source-segments", *sorted(owners))
            slots.append(
                SpatialSlot(
                    start=left - matrix_left,
                    end=right - matrix_left,
                    value=(
                        payload_value
                        if owners and not explicitly_empty
                        else EMPTY
                    ),
                )
            )
            owners_by_slot.append([] if explicitly_empty else owners)
        materialized.append((top, bottom, tuple(slots), owners_by_slot))

    codes: list[tuple[int, ...]] = []
    group_start = 0
    for index in range(1, len(materialized) + 1):
        boundary = index == len(materialized) or (
            materialized[index - 1][1] != materialized[index][0]
        )
        if not boundary:
            continue
        codes.extend(
            encode_spatial_topology(
                tuple(value[2] for value in materialized[group_start:index])
            )
        )
        group_start = index
    maximum_segments = max((len(value[2]) for value in materialized), default=0)
    serialized_rows: list[dict[str, object]] = []
    for index, ((top, bottom, slots, owners), row_codes) in enumerate(
        zip(materialized, codes, strict=True)
    ):
        serialized_rows.append(
            {
                "row": index,
                "y": [top - crop_top, bottom - crop_top],
                "matrix_y": [top - matrix_top, bottom - matrix_top],
                "segments": [
                    {
                        "column": column,
                        "x": [
                            slot.start + matrix_left - crop_left,
                            slot.end + matrix_left - crop_left,
                        ],
                        "matrix_x": [slot.start, slot.end],
                        "state": "empty" if slot.value is EMPTY else "payload",
                        "code": row_codes[column],
                        "source_segment_ids": owners[column],
                    }
                    for column, slot in enumerate(slots)
                ],
                "compressed_codes": [*row_codes, None],
                "null_tail": {
                    "from_column": len(row_codes),
                    "through_column_exclusive": maximum_segments,
                    "repeat_last_code": row_codes[-1] if row_codes else None,
                },
            }
        )
    represented_segment_ids = {
        segment_id
        for row in serialized_rows
        for segment in row["segments"]
        for segment_id in segment["source_segment_ids"]
    }
    if represented_segment_ids != set(document_object.segment_ids):
        missing = sorted(set(document_object.segment_ids) - represented_segment_ids)
        raise ValueError(
            "object-local matrix must represent every owned source segment; "
            f"missing={','.join(missing)}"
        )
    return {
        "schema": "object-local-sparse-topology-v1",
        "object_id": document_object.object_id,
        "kind": document_object.kind,
        "matrix_basis": document_object.matrix_basis.value,
        "coordinate_space": "object-crop-pixels",
        "crop_bbox_on_page": list(document_object.bbox),
        "matrix_bbox_on_page": list(document_object.matrix_bbox),
        "matrix_bbox_in_crop": [
            matrix_left - crop_left,
            matrix_top - crop_top,
            matrix_right - crop_left,
            matrix_bottom - crop_top,
        ],
        "codes": {
            "nothing": 0,
            "merge_up": 3,
            "merge_left": 5,
            "empty": 7,
            "merge_both": 8,
        },
        "null_semantics": "repeat the last real segment code through the logical row tail",
        "rows": serialized_rows,
    }


def _font(size: int):
    for path in (
        "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
    ):
        try:
            return ImageFont.truetype(path, size=size)
        except OSError:
            continue
    return ImageFont.load_default()


def _contact_sheet(
    entries: tuple[tuple[PartitionedObject, Image.Image], ...],
    path: Path,
) -> None:
    if not entries:
        Image.new("RGB", (320, 80), "white").save(path)
        return
    thumb_width = 300
    label_height = 34
    columns = 4
    cards: list[Image.Image] = []
    for item, source in entries:
        thumbnail = source.copy()
        thumbnail.thumbnail((thumb_width, 190))
        card = Image.new(
            "RGB",
            (thumb_width, label_height + thumbnail.height),
            "white",
        )
        card.paste(thumbnail, ((thumb_width - thumbnail.width) // 2, label_height))
        ImageDraw.Draw(card).text(
            (5, 5),
            f"{item.object_id}  {item.kind}  segments={len(item.segment_ids)}",
            fill="black",
            font=_font(14),
        )
        cards.append(card)
    rows = (len(cards) + columns - 1) // columns
    row_heights = [
        max(card.height for card in cards[row * columns : (row + 1) * columns])
        for row in range(rows)
    ]
    sheet = Image.new(
        "RGB",
        (columns * thumb_width, sum(row_heights)),
        (225, 225, 225),
    )
    y = 0
    for row, row_height in enumerate(row_heights):
        for column, card in enumerate(cards[row * columns : (row + 1) * columns]):
            sheet.paste(card, (column * thumb_width, y))
        y += row_height
    sheet.save(path)


def main() -> int:
    args = parse_args()
    stage = args.stage_dir.resolve()
    topology_stage = (
        args.topology_dir.resolve()
        if args.topology_dir is not None
        else stage
    )
    topology_path = topology_stage / args.topology
    segments_path = stage / args.segments
    nodes_path = stage / args.nodes
    image_path = stage / args.image
    ownership_path = stage / args.ownership
    if not ownership_path.is_file():
        ownership_path = stage / "ownership.png"
    for path in (topology_path, segments_path, nodes_path, image_path, ownership_path):
        if not path.is_file():
            raise FileNotFoundError(path)

    rows, networks = _parse_topology(_read_json(topology_path))
    legacy_trace_path = stage / "legacy-matrix.json"
    bbox_overrides: dict[str, BoxTuple] | None = None
    if legacy_trace_path.is_file():
        legacy_trace = _read_json(legacy_trace_path)
        if not isinstance(legacy_trace, dict) or not isinstance(
            legacy_trace.get("leaves"), list
        ):
            raise ValueError("legacy v16 trace is invalid")
        bbox_overrides = {}
        for leaf in legacy_trace["leaves"]:
            if not isinstance(leaf, dict) or type(leaf.get("segment_id")) is not str:
                raise ValueError("legacy v16 leaf is invalid")
            bbox_overrides[str(leaf["segment_id"])] = _bbox(
                leaf.get("content_bbox"), name="legacy v16 content bbox"
            )
    segments = _parse_segments(
        _read_jsonl(segments_path),
        bbox_overrides=bbox_overrides,
    )
    nodes = _parse_nodes(_read_jsonl(nodes_path))
    candidates = partition_recursive_objects(
        segments=segments,
        nodes=nodes,
        rows=rows,
        networks=networks,
    )
    objects = tuple(
        item for item in candidates if has_two_dimensional_object_extent(item)
    )
    residual_candidates = tuple(
        item for item in candidates if not has_two_dimensional_object_extent(item)
    )
    segment_by_id = {segment.segment_id: segment for segment in segments}

    output = (
        args.output_dir.resolve()
        if args.output_dir is not None
        else stage.parent / "06-objects"
    )
    if output.exists():
        if not args.replace:
            raise FileExistsError(f"output already exists: {output}")
        shutil.rmtree(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    temporary = Path(tempfile.mkdtemp(prefix=f".{output.name}.partial-", dir=output.parent))
    try:
        objects_root = temporary / "objects"
        objects_root.mkdir()
        with Image.open(image_path) as opened:
            source = opened.convert("RGB")
        with Image.open(ownership_path) as opened:
            ownership = opened.convert("RGB")
        if source.size != ownership.size:
            raise ValueError("aligned image and ownership dimensions disagree")

        contact_entries: list[tuple[PartitionedObject, Image.Image]] = []
        object_records = []
        for document_object in objects:
            object_dir = objects_root / document_object.object_id
            object_dir.mkdir()
            crop = source.crop(document_object.bbox)
            ownership_crop = ownership.crop(document_object.bbox)
            crop.save(object_dir / "object.png")
            ownership_crop.save(object_dir / "ownership.png")
            matrix = _local_matrix(
                document_object=document_object,
                rows=rows,
                segment_by_id=segment_by_id,
                networks=networks,
            )
            _write_json(object_dir / "matrix.json", matrix)
            (object_dir / "matrix.txt").write_text(
                "\n".join(
                    " ".join(
                        "null" if code is None else str(code)
                        for code in row["compressed_codes"]
                    )
                    for row in matrix["rows"]
                )
                + "\n",
                encoding="utf-8",
            )
            record = {
                "object_id": document_object.object_id,
                "kind": document_object.kind,
                "matrix_basis": document_object.matrix_basis.value,
                "bbox": list(document_object.bbox),
                "matrix_bbox": list(document_object.matrix_bbox),
                "segment_ids": list(document_object.segment_ids),
                "evidence": list(document_object.evidence),
                "files": {
                    "image": "object.png",
                    "ownership": "ownership.png",
                    "matrix": "matrix.json",
                    "matrix_text": "matrix.txt",
                },
            }
            _write_json(object_dir / "object.json", record)
            object_records.append(record)
            contact_entries.append((document_object, crop))

        _contact_sheet(tuple(contact_entries), temporary / "contact-sheet.png")
        residual_records = [
            {
                "residual_id": f"residual-{index:06d}",
                "source_candidate_id": item.object_id,
                "matrix_basis": item.matrix_basis.value,
                "bbox": list(item.bbox),
                "segment_ids": list(item.segment_ids),
                "reason": (
                    "wide-thin-page-edge-fringe"
                    if item.kind == "structural-residual"
                    else "no-two-dimensional-object-extent"
                ),
                "accounting_role": "geometry-only; excluded from objects",
            }
            for index, item in enumerate(residual_candidates)
        ]
        object_segment_ids = {
            segment_id
            for item in objects
            for segment_id in item.segment_ids
        }
        residual_segment_ids = {
            segment_id
            for item in residual_candidates
            for segment_id in item.segment_ids
        }
        exact_accounting = (
            object_segment_ids.isdisjoint(residual_segment_ids)
            and object_segment_ids | residual_segment_ids == set(segment_by_id)
        )
        manifest = {
            "schema": "recursive-topology-objects-v2",
            "semantic_stage": 6,
            "stage_name": "recursive-topology-object-partition",
            "partition_candidates": len(candidates),
            "objects": len(objects),
            "tables": sum(item.kind == "table" for item in objects),
            "rule_lattice_matrices": sum(
                item.matrix_basis is PartitionMatrixBasis.RULE_LATTICE
                for item in objects
            ),
            "topology_slice_matrices": sum(
                item.matrix_basis is PartitionMatrixBasis.TOPOLOGY_SLICE
                for item in objects
            ),
            "flow_objects": sum(item.kind == "flow" for item in objects),
            "paragraphs": sum(item.kind == "paragraph" for item in objects),
            "lists": sum(item.kind == "list" for item in objects),
            "residual_candidates": len(residual_candidates),
            "source_segments": len(segments),
            "object_segments": len(object_segment_ids),
            "residual_segments": len(residual_segment_ids),
            "exact_accounting": exact_accounting,
            "objects_exclude_structural_residuals": True,
            "inputs": {
                "topology": str(topology_path),
                "segments": str(segments_path),
                "nodes": str(nodes_path),
                "image": str(image_path),
                "legacy_trace": (
                    str(legacy_trace_path) if legacy_trace_path.is_file() else None
                ),
            },
            "isolation": "artifact-only; no Stage 1, OCR, Stage 5, or Stage 7 execution",
            "objects_index": "objects.jsonl",
            "residuals_index": "residuals.jsonl",
            "contact_sheet": "contact-sheet.png",
        }
        _write_json(temporary / "manifest.json", manifest)
        (temporary / "methodology.txt").write_text(
            "\n".join(
                (
                    "Recursive topology object partition",
                    "1. Consume only stored Stage 1 nodes/segments and canonical numeric topology.",
                    "2. Before typing anything, find finite 7/10 corridors spanning each recursive camera.",
                    "3. Split payload on both sides of those corridors without inspecting either side's type.",
                    "4. Keep synchronized parallel row tracks as one layout grid; otherwise retain separate chambers.",
                    "5. A finite mixed-axis cycle proves only a two-dimensional topology footprint, not a table.",
                    (
                        "6. A table requires that cycle plus an independently "
                        "detected structural lattice with the same finite extent."
                    ),
                    "7. 0 5 / 3 8 is only the locally normalized spelling of the smallest cycle candidate.",
                    "8. Raw 0 5 / 8 8 has an incoming left edge: expand it left or reject the incomplete crop.",
                    "9. Ordinal null padding has no physical X extent and is never invented as an object boundary.",
                    (
                        "10. A cycle without lattice support remains ordinary "
                        "flow/list geometry and preclaims no segments."
                    ),
                    "11. Preserve source connectivity when rebuilding local matrices; never merge all owned payload.",
                    "12. Keep local empty segments explicit and append null only after the final finite segment.",
                    "13. Partition remaining payload bottom-up inside the retained recursive tree.",
                    "14. Treat repeated marker/body lanes as lists unless a structural lattice proves a table.",
                    "15. Keep degenerate geometry in residuals rather than creating empty object folders.",
                    "16. Require exact one-place accounting of every Stage 1 segment across objects and residuals.",
                    "17. Do not execute geometry, OCR, block planning, or document assembly.",
                    "",
                )
            ),
            encoding="utf-8",
        )
        (temporary / "objects.jsonl").write_text(
            "\n".join(
                json.dumps(record, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
                for record in object_records
            )
            + ("\n" if object_records else ""),
            encoding="utf-8",
        )
        (temporary / "residuals.jsonl").write_text(
            "\n".join(
                json.dumps(record, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
                for record in residual_records
            )
            + ("\n" if residual_records else ""),
            encoding="utf-8",
        )
        if not exact_accounting:
            raise ValueError("objects and residuals must exactly account for Stage 1 segments")
        temporary.rename(output)
    except Exception:
        shutil.rmtree(temporary, ignore_errors=True)
        raise

    print(output)
    print(
        f"objects={len(objects)} tables={sum(item.kind == 'table' for item in objects)} "
        f"object_segments={sum(len(item.segment_ids) for item in objects)} "
        f"residuals={len(residual_candidates)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
